name: Amis Creperie + Cafe
favicon: null
layout_spectrum: 0.3649
typography_spectrum: 0.62614
title: 'Advocate Community, Source Locally, Operate Sustainably'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#73594c'
    - '#ffd35c'
    - '#f26f39'
    - '#bdb1aa'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
