name: Amis Creperie + Cafe
favicon: null
layout_spectrum: 0.05471229110844433
typography_spectrum: 0.7758055145386606
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#72594c'
    - '#ffd35c'
    - '#f36f3a'
    - '#000000'
    - '#ff0000'
  brandStrength: 0.75
  lightness: 0.01468102796934545
  saturation: 0.875
  rhythmicContrast: 0.5175062471535057
purpose: []
